### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by Roh7771** [Roh7771/postsWithPolling#1]

**Comment by coursar** [comment]
Всё круто, но зачем сортировка по id? На случай, если сервер отдаст вам в неправильном порядке?

**Comment by Roh7771** [comment]
Мой сервер возвращает массив постов в порядке увеличения id постов, поэтому я предварительно сортирую их в порядке уменьшения id, чтобы при переборе массива метод appendChild добавлял посты в DOM в правильном порядке.

**Comment by coursar** [comment]
Не проще ли с сервера в нужно порядке возвращать? ))

**Comment by Roh7771** [comment]
Да, можно и так сделать, но как лучше? Как делают на практике?

**Comment by coursar** [comment]
На практике зависит от ситуации - если сервер пишет адекватный программист, то он сразу возвращает в нужном порядке ))
